name = "Tufte-Dark"
license = "MIT"
licenselink = "https://github.com/Seanny123/hugo-tufte-dark/blob/master/LICENSE.md"
description = "A minimalist blog theme using Tufte-css."
homepage = "https://github.com/Seanny123/hugo-tufte-dark"
tags = ["blog", "tufte", "minimal", "dark"]
features = ["math", "tufte-css", "tufte"]
min_version = 0.15

[author]
  name = "Sean Aubin"
  homepage = "https://seanny123.github.io"
